#!/usr/bin/env python3
"""Search for alternating plane graphs over states that are planar by construction.

Two earlier lanes -- `closed_map_search.py` and the annealer in
`general_apg.py` -- search the space of rotation systems by two-edge switches
and both plateau.  The reason is measured, not guessed: at the plateau every
*local* condition is already satisfied -- degree alternation, face alternation,
face sizes, simplicity, simple facial walks all score zero -- and the whole
residual penalty is genus.  A typical stuck state at order 20 had 17 faces where
Euler demands 25.  A two-edge switch moves the face count globally, so the
search wanders over higher-genus maps and never lands on the sphere.

So this lane never leaves the sphere.  The state is a plane triangulation `T`
on `n` vertices together with a set `D` of deleted edges; the graph searched is
`T - D`.  Both moves preserve planarity:

* **flip** the diagonal of the quadrilateral formed by two triangles of `T`;
* **toggle** an edge of `T` in or out of `D`.

The objective then only has to score the alternating conditions, since
planarity, connectivity and the Euler count come free.

Triangulations are generated by the standard incremental insertion: start from
the tetrahedron and repeatedly place a vertex inside a face, joined to its three
corners.
"""
from __future__ import annotations

import argparse
import json
import math
import random
from pathlib import Path


def random_triangulation(order: int, rng: random.Random) -> dict[int, list[int]]:
    """A plane triangulation on `order` vertices as a clockwise rotation system.

    Insertion has to respect the embedding, not just the abstract graph.  With
    the predecessor face rule used throughout this directory, the facial walk
    `a -> b -> c -> a` has `b` immediately before `c` in a's ring, `c` before
    `a` in b's, and `a` before `b` in c's; the new vertex goes into each of
    those three gaps.  `test_plane_apg_search.py` checks the result really is a
    sphere with every face a triangle.
    """

    rotation: dict[int, list[int]] = {
        0: [1, 2, 3], 1: [0, 3, 2], 2: [0, 1, 3], 3: [0, 2, 1]
    }
    for vertex in range(4, order):
        walks = facial_walks(rotation)
        walk = walks[rng.randrange(len(walks))]
        a, b, c = (dart[0] for dart in walk)
        for x, before in ((a, b), (b, c), (c, a)):
            ring = rotation[x]
            ring.insert(ring.index(before) + 1, vertex)
        rotation[vertex] = [a, b, c]
    return rotation


def facial_walks(rotation: dict[int, list[int]]) -> list[list[int]]:
    predecessor = {}
    for vertex, ring in rotation.items():
        for index, neighbour in enumerate(ring):
            predecessor[(vertex, neighbour)] = ring[index - 1]
    walks, seen = [], set()
    for dart in predecessor:
        if dart in seen:
            continue
        walk, cursor = [], dart
        while cursor not in seen:
            seen.add(cursor)
            walk.append(cursor)
            cursor = (cursor[1], predecessor[(cursor[1], cursor[0])])
        walks.append(walk)
    return walks


def delete(rotation: dict[int, list[int]], removed: set) -> dict[int, list[int]]:
    out = {}
    for vertex, ring in rotation.items():
        kept = [n for n in ring
                if (min(vertex, n), max(vertex, n)) not in removed]
        out[vertex] = kept
    return out


def penalty(rotation: dict[int, list[int]]) -> int:
    """Zero exactly when this plane graph is an alternating plane graph."""

    total = 0
    for vertex, ring in rotation.items():
        if len(ring) < 3:
            total += 3 - len(ring)
    walks = facial_walks(rotation)
    size_of = {}
    for walk in walks:
        for dart in walk:
            size_of[dart] = len(walk)
        corners = [dart[0] for dart in walk]
        if len(walk) < 3:
            total += 3 - len(walk)
        total += len(corners) - len(set(corners))
    degree = {vertex: len(ring) for vertex, ring in rotation.items()}
    for vertex, ring in rotation.items():
        for neighbour in ring:
            if degree[vertex] == degree[neighbour]:
                total += 1                      # counted once per direction
            if size_of[(vertex, neighbour)] == size_of[(neighbour, vertex)]:
                total += 1
    return total


def _edges(rotation: dict[int, list[int]]) -> list[tuple[int, int]]:
    return sorted({(min(v, n), max(v, n)) for v, ring in rotation.items() for n in ring})


def search(order: int, seed: int, restarts: int, steps: int):
    rng = random.Random(seed)
    for _ in range(restarts):
        triangulation = random_triangulation(order, rng)
        edges = _edges(triangulation)
        removed: set = set()
        current = penalty(delete(triangulation, removed))
        for step in range(steps):
            if current == 0:
                return delete(triangulation, removed)
            temperature = max(0.05, 2.0 * (0.02 / 2.0) ** (step / steps))
            edge = edges[rng.randrange(len(edges))]
            if edge in removed:
                removed.discard(edge)
            else:
                removed.add(edge)
            candidate = penalty(delete(triangulation, removed))
            if candidate <= current or rng.random() < math.exp(
                (current - candidate) / temperature
            ):
                current = candidate
            else:
                if edge in removed:
                    removed.discard(edge)
                else:
                    removed.add(edge)
        if current == 0:
            return delete(triangulation, removed)
    return None


def to_certificate(rotation: dict[int, list[int]]) -> dict:
    labels = {v: i for i, v in enumerate(sorted(rotation))}
    rows = []
    for vertex in sorted(rotation, key=lambda v: labels[v]):
        ring = [labels[n] for n in rotation[vertex]]
        start = ring.index(min(ring))
        rows.append({"id": labels[vertex], "clockwise": ring[start:] + ring[:start]})
    return {"format": "apg-plane-rotation-v1", "vertices": rows}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("orders", type=int, nargs="+")
    parser.add_argument("--seed", type=int, default=20260901)
    parser.add_argument("--restarts", type=int, default=200)
    parser.add_argument("--steps", type=int, default=20_000)
    parser.add_argument("--out", type=Path)
    args = parser.parse_args()
    import connectivity as cn
    for order in args.orders:
        hit = search(order, args.seed + order, args.restarts, args.steps)
        if hit is None:
            print(f"order {order}: no hit", flush=True)
            continue
        three = cn.is_three_connected(hit)
        print(f"order {order}: FOUND, 3-connected={three}", flush=True)
        if args.out:
            args.out.mkdir(parents=True, exist_ok=True)
            name = f"APG3_{order}.json" if three else f"APG_{order}.json"
            (args.out / name).write_text(
                json.dumps(to_certificate(hit), indent=1, sort_keys=True) + "\n"
            )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
