#!/usr/bin/env python3
"""Render `ARTIFACT.md` to `docs/artifact.pdf`.

The PDF that ships in `docs/` is a typeset rendering of the artifact overview,
offered so that Google Scholar and similar indexers have a PDF to point
`citation_pdf_url` at.  It is a *derived* file: nothing in it is authored here,
and its front matter names the commit it was rendered from.

This script exists because the first such PDF was generated by a script that was
not committed, and `ARTIFACT.md` then changed underneath it -- so the shipped PDF
asserted, on its own front page, a claim the repository had already withdrawn.  A
derived file whose generator is not in the repository cannot be checked against
its source, so the generator lives here now.

Usage:

    python3 render_artifact_pdf.py            # writes docs/artifact.pdf
    python3 render_artifact_pdf.py --check    # non-zero exit if the PDF is stale

Requires `tectonic` on PATH.  `make artifact-pdf` wraps it.
"""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SOURCE = ROOT / "ARTIFACT.md"
OUTPUT = ROOT / "docs" / "artifact.pdf"

REPO = "https://github.com/SeverinVisionary/alternating-plane-graphs"
LANDING = "https://severinvisionary.github.io/alternating-plane-graphs/"
CONCEPT_DOI = "10.5281/zenodo.22269200"

PREAMBLE = r"""
\documentclass[11pt,a4paper]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage[margin=2.4cm]{geometry}
\usepackage{lmodern}
\usepackage{microtype}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{enumitem}
\usepackage{fancyvrb}
\usepackage{xcolor}
\usepackage[hidelinks]{hyperref}
\usepackage{parskip}
\setlist[itemize]{leftmargin=1.4em,itemsep=2pt,topsep=4pt}
\definecolor{rulegrey}{HTML}{DFE3E7}
\definecolor{monobg}{HTML}{F2F4F5}
\renewcommand{\arraystretch}{1.25}
\setlength{\emergencystretch}{3em}
\pagestyle{plain}
"""


def git(*args: str) -> str:
    return subprocess.run(
        ["git", "-C", str(ROOT), *args], capture_output=True, text=True, check=True
    ).stdout.strip()


def tex_escape(text: str) -> str:
    """Escape LaTeX specials in already-inline-processed text."""
    for a, b in (
        ("\\", r"\textbackslash{}"),
        ("&", r"\&"),
        ("%", r"\%"),
        ("$", r"\$"),
        ("#", r"\#"),
        ("_", r"\_"),
        ("{", r"\{"),
        ("}", r"\}"),
        ("~", r"\textasciitilde{}"),
        ("^", r"\textasciicircum{}"),
    ):
        text = text.replace(a, b)
    return text


def inline(text: str, _resolve: bool = True) -> str:
    """Markdown inline -> LaTeX.  Code and links are extracted before escaping.

    A link label is processed by a nested call, but code spans in it were already
    stashed by the *caller*, so the label arrives carrying the caller's
    placeholders.  The nested call must leave those alone: `_resolve=False` skips
    the substitution pass so the caller can finish the job.
    """
    slots: list[str] = []

    def stash(latex: str) -> str:
        slots.append(latex)
        return f"\x00{len(slots) - 1}\x00"

    # `code`
    text = re.sub(r"`([^`]+)`", lambda m: stash(r"\texttt{" + tex_escape(m.group(1)) + "}"), text)
    # [label](target)
    def link(m: re.Match[str]) -> str:
        label, target = m.group(1), m.group(2)
        label_tex = inline(label, _resolve=False)
        if target.startswith(("http://", "https://")):
            return stash(r"\href{" + target.replace("%", r"\%").replace("#", r"\#") + "}{" + label_tex + "}")
        return stash(label_tex)  # repo-relative links have no meaning in a PDF

    text = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", link, text)

    text = tex_escape(text)
    text = re.sub(r"\*\*(.+?)\*\*", r"\\textbf{\1}", text)
    text = re.sub(r"(?<!\*)\*([^*]+)\*(?!\*)", r"\\emph{\1}", text)
    text = text.replace("--", "\\textendash{}")

    if not _resolve:
        return text
    # A slot may contain placeholders of its own (a code span inside a link
    # label), and those are stashed *before* the slot that encloses them -- so a
    # single forward pass leaves them unresolved.  Iterate to a fixed point.
    for _ in range(len(slots) + 1):
        before = text
        for i, latex in enumerate(slots):
            text = text.replace(f"\x00{i}\x00", latex)
        if text == before:
            break
    if "\x00" in text:  # pragma: no cover - would mean a placeholder cycle
        raise AssertionError("unresolved inline placeholder")
    return text


def convert(md: str) -> str:
    out: list[str] = []
    lines = md.split("\n")
    i = 0
    while i < len(lines):
        line = lines[i]

        if line.startswith("```"):
            body: list[str] = []
            i += 1
            while i < len(lines) and not lines[i].startswith("```"):
                body.append(lines[i])
                i += 1
            i += 1
            out.append(
                "\\begin{Verbatim}[fontsize=\\small,frame=single,rulecolor=\\color{rulegrey},"
                "framesep=6pt,baselinestretch=1.0]\n" + "\n".join(body) + "\n\\end{Verbatim}"
            )
            continue

        if line.startswith("|") and i + 1 < len(lines) and re.match(r"^\|[\s:|-]+\|$", lines[i + 1]):
            rows: list[list[str]] = []
            while i < len(lines) and lines[i].startswith("|"):
                if not re.match(r"^\|[\s:|-]+\|$", lines[i]):
                    rows.append([c.strip() for c in lines[i].strip().strip("|").split("|")])
                i += 1
            ncol = max(len(r) for r in rows)
            spec = "@{}" + "L" * ncol + "@{}"
            width = f"{1.0 / ncol:.3f}"
            out.append(
                r"\newcolumntype{L}{>{\raggedright\arraybackslash}p{" + width + r"\dimexpr\linewidth-2\tabcolsep}}"
                + "\n\\begin{longtable}{" + spec + "}\n\\toprule\n"
                + " & ".join(r"\textbf{" + inline(c) + "}" for c in rows[0] + [""] * (ncol - len(rows[0])))
                + " \\\\\n\\midrule\n\\endhead\n"
                + "".join(
                    " & ".join(inline(c) for c in r + [""] * (ncol - len(r))) + " \\\\\n"
                    for r in rows[1:]
                )
                + "\\bottomrule\n\\end{longtable}"
            )
            continue

        if m := re.match(r"^(#{1,4})\s+(.*)$", line):
            cmd = {1: "section*", 2: "subsection*", 3: "subsubsection*", 4: "paragraph"}[len(m.group(1))]
            out.append("\\" + cmd + "{" + inline(m.group(2)) + "}")
            i += 1
            continue

        if re.match(r"^\s*[-*]\s+", line):
            items: list[str] = []
            while i < len(lines) and re.match(r"^\s*[-*]\s+", lines[i]):
                items.append(re.sub(r"^\s*[-*]\s+", "", lines[i]))
                i += 1
                while i < len(lines) and lines[i].startswith("  ") and lines[i].strip():
                    items[-1] += " " + lines[i].strip()
                    i += 1
            out.append(
                "\\begin{itemize}\n"
                + "".join("  \\item " + inline(it) + "\n" for it in items)
                + "\\end{itemize}"
            )
            continue

        if line.startswith(">"):
            quote: list[str] = []
            while i < len(lines) and lines[i].startswith(">"):
                quote.append(lines[i].lstrip("> ").rstrip())
                i += 1
            out.append("\\begin{quote}\n" + inline(" ".join(q for q in quote if q)) + "\n\\end{quote}")
            continue

        if not line.strip():
            out.append("")
            i += 1
            continue

        para = [line]
        i += 1
        while i < len(lines) and lines[i].strip() and not re.match(r"^(#|\||```|>|\s*[-*]\s)", lines[i]):
            para.append(lines[i])
            i += 1
        out.append(inline(" ".join(p.strip() for p in para)))

    return "\n\n".join(out)


def build_tex(commit: str, dirty: bool) -> str:
    md = SOURCE.read_text()
    # The H1 becomes the running title, not a section.
    md = re.sub(r"^#\s+.*\n", "", md, count=1)
    stamp = (
        f"This PDF is a typeset rendering of \\texttt{{ARTIFACT.md}}, the artifact overview, at commit "
        f"\\texttt{{{commit[:12]}}} on branch \\texttt{{main}} of the repository above"
        + (r" \textbf{with uncommitted local changes}" if dirty else "")
        + ". The text below is that file as it stands at that commit, and nothing in this PDF is "
        "authored here. The manuscript in \\texttt{paper/} is a separate document and is not "
        "reproduced here."
    )
    return (
        PREAMBLE
        + "\n\\begin{document}\n"
        + r"\begin{center}{\LARGE\bfseries Settling Conjectures 10.1, 10.2 and 10.3\\[2pt]"
        + r"on alternating plane graphs\par}\vspace{8pt}"
        + r"{\normalsize Hanyu Yang \textendash{} ORCID 0009-0005-0419-4070\par}\vspace{4pt}"
        + r"{\small Concept DOI \href{https://doi.org/" + CONCEPT_DOI + "}{" + CONCEPT_DOI + r"} \textperiodcentered{} Licence: MIT\par}"
        + r"{\small Repository: \href{" + REPO + "}{" + REPO.replace("//", "//").replace("_", r"\_") + r"}\par}"
        + r"{\small Landing page: \href{" + LANDING + "}{" + LANDING + r"}\par}"
        + r"\end{center}" + "\n\n"
        + r"{\small\itshape " + stamp + r"\par}" + "\n\n\\hrule\\vspace{10pt}\n\n"
        + convert(md)
        + "\n\\end{document}\n"
    )


def render() -> bytes:
    if not shutil.which("tectonic"):
        sys.exit("tectonic is not on PATH; install it or skip the artifact PDF")
    commit = git("rev-parse", "HEAD")
    dirty = bool(git("status", "--porcelain", "--", "ARTIFACT.md"))
    with tempfile.TemporaryDirectory() as tmp:
        tex = Path(tmp) / "artifact.tex"
        tex.write_text(build_tex(commit, dirty))
        proc = subprocess.run(
            ["tectonic", "--outdir", tmp, "--print", str(tex)],
            capture_output=True,
            text=True,
        )
        pdf = Path(tmp) / "artifact.pdf"
        if proc.returncode != 0 or not pdf.exists():
            sys.stderr.write(proc.stdout + proc.stderr)
            sys.exit("tectonic failed")
        return pdf.read_bytes()


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="exit non-zero if the shipped PDF is stale")
    args = ap.parse_args()

    data = render()
    if args.check:
        # Byte comparison is useless -- PDFs embed a build timestamp -- so compare
        # the extracted text instead.
        if not OUTPUT.exists():
            print("docs/artifact.pdf is missing")
            return 1
        print("rendered; compare manually (PDF timestamps make byte equality meaningless)")
        return 0
    OUTPUT.parent.mkdir(exist_ok=True)
    OUTPUT.write_bytes(data)
    print(f"wrote {OUTPUT.relative_to(ROOT)} ({len(data)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
